//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialCommunication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubeData
    {
        public long Id { get; set; }
        public string Guid { get; set; }
        public string RawValue { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string BarCode { get; set; }
        public string MachineId { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
